// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Helloworld struct {
	Id                   *int32   `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Str                  *string  `protobuf:"bytes,2,req,name=str" json:"str,omitempty"`
	Opt                  *int32   `protobuf:"varint,3,opt,name=opt" json:"opt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Helloworld) Reset()         { *m = Helloworld{} }
func (m *Helloworld) String() string { return proto.CompactTextString(m) }
func (*Helloworld) ProtoMessage()    {}
func (*Helloworld) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *Helloworld) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Helloworld.Unmarshal(m, b)
}
func (m *Helloworld) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Helloworld.Marshal(b, m, deterministic)
}
func (m *Helloworld) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Helloworld.Merge(m, src)
}
func (m *Helloworld) XXX_Size() int {
	return xxx_messageInfo_Helloworld.Size(m)
}
func (m *Helloworld) XXX_DiscardUnknown() {
	xxx_messageInfo_Helloworld.DiscardUnknown(m)
}

var xxx_messageInfo_Helloworld proto.InternalMessageInfo

func (m *Helloworld) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Helloworld) GetStr() string {
	if m != nil && m.Str != nil {
		return *m.Str
	}
	return ""
}

func (m *Helloworld) GetOpt() int32 {
	if m != nil && m.Opt != nil {
		return *m.Opt
	}
	return 0
}

func init() {
	proto.RegisterType((*Helloworld)(nil), "protobuf.helloworld")
}

func init() {
	proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2)
}

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 100 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc8, 0x48, 0xcd, 0xc9,
	0xc9, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x00, 0x53,
	0x49, 0xa5, 0x69, 0x4a, 0x0e, 0x5c, 0x5c, 0x08, 0x59, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09,
	0x46, 0x05, 0x26, 0x0d, 0xd6, 0x20, 0xa6, 0xcc, 0x14, 0x21, 0x01, 0x2e, 0xe6, 0xe2, 0x92, 0x22,
	0x09, 0x26, 0x05, 0x26, 0x0d, 0xce, 0x20, 0x10, 0x13, 0x24, 0x92, 0x5f, 0x50, 0x22, 0xc1, 0xac,
	0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0x62, 0x02, 0x02, 0x00, 0x00, 0xff, 0xff, 0x06, 0xda, 0xdb, 0xa3,
	0x5e, 0x00, 0x00, 0x00,
}
