// Code generated by protoc-gen-go. DO NOT EDIT.
// source: base/search.proto

package base

import (
	"fmt"
	"github.com/golang/protobuf/proto"
	"math"
	//other "gopiano/com/wolf/piano/test/protobuf/other"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SearchRequest_Corpus int32

const (
	SearchRequest_UNIVERSAL SearchRequest_Corpus = 0
	SearchRequest_WEB       SearchRequest_Corpus = 1
	SearchRequest_IMAGES    SearchRequest_Corpus = 2
	SearchRequest_LOCAL     SearchRequest_Corpus = 3
	SearchRequest_NEWS      SearchRequest_Corpus = 4
	SearchRequest_PRODUCTS  SearchRequest_Corpus = 5
	SearchRequest_VIDEO     SearchRequest_Corpus = 6
)

var SearchRequest_Corpus_name = map[int32]string{
	0: "UNIVERSAL",
	1: "WEB",
	2: "IMAGES",
	3: "LOCAL",
	4: "NEWS",
	5: "PRODUCTS",
	6: "VIDEO",
}

var SearchRequest_Corpus_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
	"LOCAL":     3,
	"NEWS":      4,
	"PRODUCTS":  5,
	"VIDEO":     6,
}

func (x SearchRequest_Corpus) String() string {
	return proto.EnumName(SearchRequest_Corpus_name, int32(x))
}

func (SearchRequest_Corpus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ae4de28b5d41fd07, []int{0, 0}
}

type SearchRequest struct {
	Query                string               `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber           int32                `protobuf:"varint,2,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	ResultPerPage        int32                `protobuf:"varint,3,opt,name=result_per_page,json=resultPerPage,proto3" json:"result_per_page,omitempty"`
	Corpus               SearchRequest_Corpus `protobuf:"varint,4,opt,name=corpus,proto3,enum=base.SearchRequest_Corpus" json:"corpus,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae4de28b5d41fd07, []int{0}
}

func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (m *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(m, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchRequest) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *SearchRequest) GetResultPerPage() int32 {
	if m != nil {
		return m.ResultPerPage
	}
	return 0
}

func (m *SearchRequest) GetCorpus() SearchRequest_Corpus {
	if m != nil {
		return m.Corpus
	}
	return SearchRequest_UNIVERSAL
}

type SearchResponse struct {
	// 包名.消息
	Results              []*other.Result3 `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae4de28b5d41fd07, []int{1}
}

func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (m *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(m, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetResults() []*other.Result3 {
	if m != nil {
		return m.Results
	}
	return nil
}

// 嵌套
type SearchResponse_Result2 struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Snippets             []string `protobuf:"bytes,3,rep,name=snippets,proto3" json:"snippets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchResponse_Result2) Reset()         { *m = SearchResponse_Result2{} }
func (m *SearchResponse_Result2) String() string { return proto.CompactTextString(m) }
func (*SearchResponse_Result2) ProtoMessage()    {}
func (*SearchResponse_Result2) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae4de28b5d41fd07, []int{1, 0}
}

func (m *SearchResponse_Result2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse_Result2.Unmarshal(m, b)
}
func (m *SearchResponse_Result2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse_Result2.Marshal(b, m, deterministic)
}
func (m *SearchResponse_Result2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse_Result2.Merge(m, src)
}
func (m *SearchResponse_Result2) XXX_Size() int {
	return xxx_messageInfo_SearchResponse_Result2.Size(m)
}
func (m *SearchResponse_Result2) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse_Result2.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse_Result2 proto.InternalMessageInfo

func (m *SearchResponse_Result2) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SearchResponse_Result2) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchResponse_Result2) GetSnippets() []string {
	if m != nil {
		return m.Snippets
	}
	return nil
}

func init() {
	proto.RegisterEnum("base.SearchRequest_Corpus", SearchRequest_Corpus_name, SearchRequest_Corpus_value)
	proto.RegisterType((*SearchRequest)(nil), "base.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "base.SearchResponse")
	proto.RegisterType((*SearchResponse_Result2)(nil), "base.SearchResponse.Result2")
}

func init() {
	proto.RegisterFile("base/search.proto", fileDescriptor_ae4de28b5d41fd07)
}

var fileDescriptor_ae4de28b5d41fd07 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcd, 0x6a, 0xc2, 0x40,
	0x14, 0x85, 0x3b, 0xe6, 0x47, 0x73, 0xad, 0x76, 0x3a, 0xb8, 0x08, 0xd9, 0x34, 0xb8, 0x28, 0x59,
	0x45, 0x1a, 0x9f, 0xc0, 0x6a, 0x28, 0x82, 0x7f, 0x4c, 0xaa, 0x42, 0x37, 0x12, 0xe5, 0xa2, 0x82,
	0x35, 0x71, 0x26, 0x59, 0xf4, 0x11, 0xfa, 0xd2, 0xa5, 0x64, 0x46, 0x0b, 0xdd, 0xcd, 0xf9, 0xce,
	0x81, 0x39, 0x9c, 0x0b, 0x8f, 0xdb, 0x54, 0x62, 0x4f, 0x62, 0x2a, 0x76, 0x87, 0x30, 0x17, 0x59,
	0x91, 0x31, 0xb3, 0x42, 0x5e, 0x27, 0x2b, 0x0e, 0x28, 0x7a, 0x02, 0x2f, 0x25, 0xca, 0xe2, 0x45,
	0x7b, 0xdd, 0x1f, 0x02, 0xad, 0x44, 0x85, 0xb9, 0x36, 0x58, 0x07, 0xac, 0x4b, 0x89, 0xe2, 0xcb,
	0x25, 0x3e, 0x09, 0x1c, 0xae, 0x05, 0x7b, 0x82, 0x66, 0x9e, 0xee, 0x71, 0x73, 0x2e, 0x3f, 0xb7,
	0x28, 0xdc, 0x9a, 0x4f, 0x02, 0x8b, 0x43, 0x85, 0x66, 0x8a, 0xb0, 0x67, 0x78, 0x10, 0x28, 0xcb,
	0x53, 0xb1, 0xc9, 0x51, 0x6c, 0x2a, 0xc3, 0x35, 0x54, 0xa8, 0xa5, 0xf1, 0x02, 0xc5, 0x22, 0xdd,
	0x23, 0x8b, 0xc0, 0xde, 0x65, 0x22, 0x2f, 0xa5, 0x6b, 0xfa, 0x24, 0x68, 0x47, 0x5e, 0x58, 0xb5,
	0x0b, 0xff, 0x75, 0x08, 0x87, 0x2a, 0xc1, 0xaf, 0xc9, 0xee, 0x07, 0xd8, 0x9a, 0xb0, 0x16, 0x38,
	0xcb, 0xd9, 0x78, 0x15, 0xf3, 0x64, 0x30, 0xa1, 0x77, 0xac, 0x0e, 0xc6, 0x3a, 0x7e, 0xa5, 0x84,
	0x01, 0xd8, 0xe3, 0xe9, 0xe0, 0x2d, 0x4e, 0x68, 0x8d, 0x39, 0x60, 0x4d, 0xe6, 0xc3, 0xc1, 0x84,
	0x1a, 0xac, 0x01, 0xe6, 0x2c, 0x5e, 0x27, 0xd4, 0x64, 0xf7, 0xd0, 0x58, 0xf0, 0xf9, 0x68, 0x39,
	0x7c, 0x4f, 0xa8, 0x55, 0x45, 0x56, 0xe3, 0x51, 0x3c, 0xa7, 0x76, 0xf7, 0x9b, 0x40, 0xfb, 0xf6,
	0xb9, 0xcc, 0xb3, 0xb3, 0x44, 0x16, 0x40, 0x5d, 0x77, 0x96, 0x2e, 0xf1, 0x8d, 0xa0, 0x19, 0xb5,
	0x43, 0xb5, 0x5d, 0xc8, 0x15, 0xed, 0xf3, 0x9b, 0xed, 0x4d, 0xa1, 0xae, 0x59, 0xc4, 0x28, 0x18,
	0xa5, 0x38, 0x5d, 0x47, 0xab, 0x9e, 0xd5, 0x90, 0xc5, 0xb1, 0x38, 0xa1, 0x1a, 0xcb, 0xe1, 0x5a,
	0x30, 0x0f, 0x1a, 0xf2, 0x7c, 0xcc, 0x73, 0x2c, 0xa4, 0x6b, 0xf8, 0x46, 0xe0, 0xf0, 0x3f, 0xbd,
	0xb5, 0xd5, 0x4d, 0xfa, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe5, 0x6a, 0x53, 0xc0, 0xc4, 0x01,
	0x00, 0x00,
}
